### PR TITLE
[#6] Added contribution guidelines in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Coderx85**
[#6] Added contribution guidelines in CONTRIBUTING.md. 
This addresses the need for clear directives, streamlining collaboration. Contributors can now refer to the guidelines, enhancing the development process. Tested locally to ensure effectiveness.

### CODE REVIEW

**Comment by nraychaudhuri** [comment]
I love this, thank you. @Priyanshu085  

Could you please use this template instead? https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

**Comment by Priyanshu085** [comment]
Okay, I will consider your preferred one.

**Comment by Priyanshu085** [comment]
# Pull Request: Update CONTRIBUTING.md

- Clarified introduction for a welcoming atmosphere.
- Streamlined reasons for contributing to DocDevGenie.
- Simplified and clarified ground rules for contributors.
- Improved readability in "Your First Contribution" and "Getting Started" sections.
- Enhanced bug reporting and feature suggestion templates.
- Improved clarity in the code review process explanation.
- Encouraged diverse contributions in the community section.
- Aimed at creating a more user-friendly and inclusive guide.
- Changes designed to improve overall clarity and ease of use.
- Closes #6, marking a step towards a more collaborative and efficient contribution process.

**Comment by nraychaudhuri** [comment]
Looks good. Merging it. Thanks @Priyanshu085

**Comment by Coderx85** [comment]
@nraychaudhuri 
Your Welcome.

**Pull request merged**
